# This workflow deployes an ARM template
name: Deploy ARM Template
on:
  repository_dispatch:
    types: [deploy_arm_template]
jobs:
  azure-job:
    runs-on: [ubuntu-latest]
    steps:
    - name: Login to Azure
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Resource Group
      env:
        LOCATION: ${{ github.event.client_payload.location }},
        RESOURCE_GROUP: ${{ github.event.client_payload.resourceGroupName }}
      if: ${{ github.event.client_payload.location != null && github.event.client_payload.resourceGroupName != '' }}
      run: |
        subscriptionId=$(az account show --query id --output tsv)
        if ! az group show --name "$RESOURCE_GROUP" &>/dev/null; then
            echo "No [$RESOURCE_GROUP] resource group actually exists in the [$subscriptionId] subscription"
            echo "Creating [$RESOURCE_GROUP] resource group in the [$subscriptionId] subscription..."

            # Create the resource group
            if az group create --name "$RESOURCE_GROUP" --location "$LOCATION" 1>/dev/null; then
                echo "[$RESOURCE_GROUP] resource group successfully created in the [$subscriptionId] subscription"
            else
                echo "Failed to create [$RESOURCE_GROUP] resource group in the [$subscriptionId] subscription"
                exit 1
            fi
        else
            echo "[$RESOURCE_GROUP] resource group already exists in the [$subscriptionId] subscription"
        fi
    - name: Pre Deployment Script
      uses: azure/CLI@v1
      env:
        PRE_SCRIPT_LOCATION: ${{ github.event.client_payload.preScriptLocation }}
        PRE_SCRIPT_ARGUMENT: ${{ github.event.client_payload.preScriptArgument }}
      if: ${{ github.event.client_payload.preScriptLocation != null && endsWith(github.event.client_payload.preScriptLocation, '.sh') }}
      with:
        azcliversion: latest
        inlineScript: |
          chmod +x $PRE_SCRIPT_LOCATION
          if [[ -z $PRE_SCRIPT_ARGUMENT ]]; then
            bash $PRE_SCRIPT_LOCATION
          else
            bash $PRE_SCRIPT_LOCATION $PRE_SCRIPT_ARGUMENT
          fi
    - name: Azure Resource Manager (ARM) Template Deployment JS
      uses: whiteducksoftware/azure-arm-action-js@v3
      env:
        RESOURCE_GROUP: ${{ github.event.client_payload.resourceGroupName }}
        TEMPLATE_LOCATION: ${{ github.event.client_payload.templateLocation }}
        PARAMETERS: ${{ github.event.client_payload.parameters }}"
      if: ${{ github.event.client_payload.resourceGroupName != null && github.event.client_payload.templateLocation != '' && github.event.client_payload.parameters != ''}}
      with:
        resourceGroupName: github-action-arm-rg
        templateLocation: ${{ env.TEMPLATE_LOCATION }}
        parameters: ${{ env.PARAMETERS }}
    - name: Post Deployment Script
      uses: azure/CLI@v1
      env:
        POST_SCRIPT_LOCATION: ${{ github.event.client_payload.postScriptLocation }}
        POST_SCRIPT_ARGUMENT: ${{ github.event.client_payload.postScriptArgument }}
      if: ${{ github.event.client_payload.postScriptLocation != null && endsWith(github.event.client_payload.postScriptLocation, '.sh') }}
      with:
        azcliversion: latest
        inlineScript: |
          chmod +x $POST_SCRIPT_LOCATION
          if [[ -z $POST_SCRIPT_ARGUMENT ]]; then
            bash $POST_SCRIPT_LOCATION
          else
            bash $POST_SCRIPT_LOCATION $POST_SCRIPT_ARGUMENT
          fi

