# This workflow deployes a configurable ARM template
name: Deploy ARM Template
on:
  repository_dispatch:

jobs:
  azure-job:
    runs-on: [ubuntu-latest]
    steps:
    - name: Login to Azure
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
